FROM node:18-alpine
WORKDIR /NgPixelHarbor/frontend
RUN npm install -g @angular/cli@14.2.13
COPY package*.json .
RUN npm install
COPY . .
EXPOSE 4200
CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200"]

