services:
  frontend:
    build:
      context: ./frontend
    container_name: ngpixelharbor-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: ngpixelharbor-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    container_name: ngpixelharbor-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: